### ISSUE TITLE
User can see list of pokemon based on region.

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/ajax-project#1]
## 💰 Motivation

A Pokemon Trainer needs to know all Pokemon species that have been discovered.

## 📐 Plan

Create an app that allows trainers to know what Pokemon exists in which region.

## 🖼️ Wireframe

<img width="941" alt="Screen Shot 2021-02-22 at 5 46 23 PM" src="https://user-images.githubusercontent.com/76749207/108792360-ee7fc700-7535-11eb-9241-2c428c98281a.png">

## ✅ Task List

- [x] Create div for homepage
- [x] Create div taking up 50% of viewport with red background
- [x] Created header within the div 
- [x] Create black horizontal bar in middle of viewport (experiment with another div or border-bottom.)
- [x] Create circle button with press me text. Center with position: absolute 
- [x] Add black border around button. 
- [x] Create transparent modal over pokeball background 
- [x] Add event listener for button click will change view to modal/region list view and remove homepage text. 
- [x] Create 3 buttons/links for Kanto, Johto, and Caught view.
- [x] Add event listener for div containing 3 buttons
- [x] Create 2nd modal (white transparent background) holding list of pokemon
   - [x] Make modal overflow to scroll
   - [x] 16 entries in view (may have to adjust)
   - [x] Make ordered list of pokemon names from API (entry_number 1 - 151)
- [x] Clicking Johto button change list of pokemon to entry_number 152 - 251
- [x] Clicking Kanto button will change list of pokemon back to Kanto list. 
- [x] Kanto view is default view. 
- [x] Get rid of inactive CSS
- [x] Double check on private window
- [x] Double check console for errors.
