### ISSUE TITLE
User can search for Pokemon

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/ajax-project#11]
## 💰 Motivation

A trainer should be able to search for a specific Pokemon.

## 📐 Plan

Create a search bar and data list to find a specific Pokemon.

## 🖼️ Wireframe

<img width="604" alt="Screen Shot 2021-02-25 at 8 13 02 PM" src="https://user-images.githubusercontent.com/76749207/109253978-e1690f00-77a5-11eb-8d5d-fd91a2158fe0.png">

## ✅ Task List

- [x] Create Search button in region container
- [x] Create div search-container, input, and datalist element in HTML as hidden.
- [x] Edit event listener to hide list container and show search container if Search button clicked
- [x] Edit  functions to add kantoList and johtoList entries to nationalList
- [x] Clicking Search will open search bar and data list of all Pokemon (need to create another array holding all Pokemon names.)
   - [x] Overflow-y choices in dropdown 
   - [x] Create function to make a new ul element holding suggestions
   - [x] Create li elements based on what user types
   - [x] Add newly created li elements to ul
   - [x] Remove ul when typing in search and replace ul with newly created ul
   - [x] Style to wireframe
- [x] Typing in search bar narrows list in dropdown.
- [x] Clicking on Pokemon name in data list will lead to Pokemon page.
