### ISSUE TITLE
User can see details of selected Pokemon

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/ajax-project#2]
## 💰 Motivation

A trainer should learn about the Pokemon they are catching.

## 📐 Plan

Create a detailed page that shows what the Pokemon looks like and facts about it.

## 🖼️ Wireframe

<img width="283" alt="Screen Shot 2021-02-22 at 5 48 52 PM" src="https://user-images.githubusercontent.com/76749207/108792495-40285180-7536-11eb-8e77-c45f33a578ef.png">

## ✅ Task List

- [x] Add event listener to list items (list container or specific region list)
- [x] Based on pokemon clicked,  receive pokemon picture, type, and flavor text from API. (use id of li element to search API)
   - [x] Create function with 2 API calls (1 for flavor text and 1 for both type and image)? 
      - [x] For flavor text, look for first property with english language in reverse loop (most updated text).
   - [x] Put collected info into a pokemon object?
- [x] Hide list views 
- [x] Remove underline from region button
- [x] Create page holding all pokemon information
- [x] Style page to wireframe
- [x] Add button to add to catch list (adding to catch list is future feature)
- [x] Add to event listener to hid pokemon page and show region list when clicking region buttons
