### ISSUE TITLE
User can save pokemon to caught list

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/ajax-project#3]
## 💰 Motivation

A trainer should be able to indicate/save what Pokemon they have caught.

## 📐 Plan

Create functionality that saves a Pokemon to a list of caught Pokemon.

## 🖼️ Wireframe

<img width="632" alt="Screen Shot 2021-02-22 at 5 52 32 PM" src="https://user-images.githubusercontent.com/76749207/108792706-c3e23e00-7536-11eb-98a0-51e254b13e31.png">

## ✅ Task List

- [x] Create data model to save pokemon to caught list
- [x] Add event listener to button to indicate pokemon is caught
   - [x] Change button appearance to indicate button pressed
   - [x] Pressing button will add pokemon to data model
- [x] Review data model to see if pokemon are being saved 
- [x] Organize caughtList array according to pokemon number
- [x] Save data model to local storage
- [x] Recover local storage on page refresh
- [x] *If user leaves pokemon page and goes back to pokemon caught, button should stay the same as it was before leaving and can't add again to data model* (maybe create 2 classes and conditional for appearance)
