### ISSUE TITLE
User can see caught Pokemon list

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/ajax-project#4]
## 💰 Motivation

A trainer should see all the Pokemon they have caught.

## 📐 Plan

Create a page that shows a list of Pokemon that the trainer has caught.

## 🖼️ Wireframe

<img width="310" alt="Screen Shot 2021-02-22 at 5 54 41 PM" src="https://user-images.githubusercontent.com/76749207/108792835-115eab00-7537-11eb-880d-155136897db1.png">

## ✅ Task List

- [x] Add to event listener to hide list and remove pokemon page when clicing caught list button (underline caught list button)
- [x] Create function to create dom of caught list
   - [x] List pokemon based on data.caughtList order.
   - [x] Display pokemon number, name, and image (inside 1 container for new event listener)
   - [x] Style list to wireframe 
- [x] Adding pokemon to data model will update caught list 
- [x] Create event listener to lead to pokemon page if clicking on name or picture (container)
   - [x] Hide caught list
   - [x] Get rid of underline on caught button
   - [x] Show pokemon page.
