### ISSUE TITLE
User can remove pokemon from caught list 

### ISSUE THREAD

**Issue by Samuel-Cho** [SamuelCho1/ajax-project#5]
## 💰 Motivation

A trainer should be able to edit the list of caught Pokemon.

## 📐 Plan

Create functionality to remove a Pokemon from the caught list.

## 🖼️ Wireframe

<img width="300" alt="Screen Shot 2021-02-22 at 5 56 46 PM" src="https://user-images.githubusercontent.com/76749207/108792972-597dcd80-7537-11eb-95ee-7d5e7d4b0aa4.png">

## ✅ Task List

- [x] Edit catchPokemon function to remove pokemon from caught list.
   - [x] Condition if catch button has 'caught' class
   - [x] Change button class to 'catch not-caught'
   - [x] Find pokemon in data model
   - [x] Remove pokemon entry from data model
   - [x] Remove pokemon entry from caught list
